imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

services:
    data_collector.apiCollectorss:
        class: AppBundle\Service\ApiCollector
        arguments: ["@rest_client"]
        tags:
            - { name: data_collector, template: "AppBundle:Manage:api-collector", id: "api-collector" }
    mail_sender:
        class: AppBundle\Service\Mailer\MailSenderMock
        arguments: [ "@validator", "@snc_redis.default" ]
        calls:
            - [ addSwiftMailer, [ "default", "@mailer.swift_mailers.default"] ]
    mailer.transport.smtp.default:
        class: AppBundle\Service\Mailer\Transport\TransportMock
    mailer.transport.smtp.secure:
        class: AppBundle\Service\Mailer\Transport\TransportMock

jms_serializer:
    metadata:
        cache: none
        debug: false
